#!/usr/bin/env python3
"""Build the SHIFT-9 hero banner as a fully-vector animated SVG.

Everything is vector — the converging light-ray burst, the focal core, and the
SHIFT-9 wordmark — so the hero is infinitely sharp at any width, ~25 KB, and
animates natively (ray shimmer, focal pulse, scan sweep), all paused under
prefers-reduced-motion. No raster, no external fetch, no font baking.

Why vector instead of a generated/photographic raster: the generated-image path
(Higgsfield) is unavailable from this environment — the result CDN is blocked by
the egress policy, so generated bytes can't be pulled in to composite + commit.
A true-vector banner is also the sharpest possible answer to "higher resolution
+ crisp vector wordmark", and the lightest. The previous photographic banner is
recoverable from git history if ever wanted.

Usage:  python3 profile/scripts/build-banner.py    # run from repo root
"""
import math
import os
import random

HERE = os.path.dirname(__file__)
OUT = os.path.normpath(os.path.join(HERE, "..", "assets", "s9-banner.svg"))

W, H = 1280, 460
FX, FY = 952, 250          # ray-burst focal point (right of centre)
VOID, INK, MUTED, SIGNAL, PULSE = "#0a0e1a", "#eef3f8", "#9aa7b8", "#22d3ee", "#8b5cf6"
MONO = "'SFMono-Regular',ui-monospace,Menlo,Consolas,monospace"
COND = "'Arial Narrow','Roboto Condensed','Helvetica Neue Condensed',Impact,sans-serif"

random.seed(9)   # deterministic output

grads, rays = [], []

# ── scattered streaks ────────────────────────────────────────────────────────
N = 34
for i in range(N):
    ang = math.radians(178 + random.uniform(-58, 58))     # fan pointing leftish
    L = random.uniform(620, 1500)
    x2, y2 = FX + L * math.cos(ang), FY + L * math.sin(ang)
    col = random.choice([INK, SIGNAL, SIGNAL, INK, PULSE])
    w = random.uniform(0.7, 3.2)
    op = random.uniform(0.18, 0.7)
    bright = random.uniform(0.7, 1.0)
    gid = f"r{i}"
    grads.append(
        f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="{FX}" y1="{FY}" x2="{x2:.0f}" y2="{y2:.0f}">'
        f'<stop offset="0" stop-color="{col}" stop-opacity="{bright:.2f}"/>'
        f'<stop offset="0.55" stop-color="{col}" stop-opacity="{bright*0.5:.2f}"/>'
        f'<stop offset="1" stop-color="{col}" stop-opacity="0"/></linearGradient>')
    rays.append(
        f'<line x1="{FX}" y1="{FY}" x2="{x2:.0f}" y2="{y2:.0f}" stroke="url(#{gid})" '
        f'stroke-width="{w:.1f}" opacity="{op:.2f}" filter="url(#soft)" '
        f'style="animation:shim {random.uniform(3.2,6.5):.1f}s ease-in-out {random.uniform(-6,0):.1f}s infinite"/>')

# ── bright "hero" streaks for definition ─────────────────────────────────────
for j, (deg, col, w, op) in enumerate([
    (-22, INK, 3.4, 0.85), (-9, SIGNAL, 2.6, 0.8),
    (8, INK, 3.0, 0.8), (20, SIGNAL, 2.4, 0.75), (-15, "#ffffff", 1.8, 0.9),
]):
    ang = math.radians(180 + deg)
    x2, y2 = FX + 1500 * math.cos(ang), FY + 1500 * math.sin(ang)
    gid = f"h{j}"
    grads.append(
        f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="{FX}" y1="{FY}" x2="{x2:.0f}" y2="{y2:.0f}">'
        f'<stop offset="0" stop-color="{col}" stop-opacity="1"/>'
        f'<stop offset="0.5" stop-color="{col}" stop-opacity="0.45"/>'
        f'<stop offset="1" stop-color="{col}" stop-opacity="0"/></linearGradient>')
    rays.append(
        f'<line x1="{FX}" y1="{FY}" x2="{x2:.0f}" y2="{y2:.0f}" stroke="url(#{gid})" '
        f'stroke-width="{w}" opacity="{op}" filter="url(#soft)" '
        f'style="animation:shim {4.5+j*0.4:.1f}s ease-in-out {-j*0.9:.1f}s infinite"/>')

stars = "".join(
    f'<circle cx="{random.randint(40, W-40)}" cy="{random.randint(30, H-30)}" '
    f'r="{random.uniform(0.5,1.4):.1f}" fill="{INK}" opacity="{random.uniform(0.15,0.5):.2f}"/>'
    for _ in range(36))

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="100%" role="img" aria-label="SHIFT-9 — Design + Engineering Studio. Code execution in motion.">
  <defs>
    <radialGradient id="halo" cx="{FX/W:.3f}" cy="{FY/H:.3f}" r="0.75">
      <stop offset="0" stop-color="{SIGNAL}" stop-opacity="0.22"/>
      <stop offset="0.5" stop-color="{PULSE}" stop-opacity="0.06"/>
      <stop offset="1" stop-color="{VOID}" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="core" cx="0.5" cy="0.5" r="0.5">
      <stop offset="0" stop-color="#ffffff" stop-opacity="1"/>
      <stop offset="0.35" stop-color="{SIGNAL}" stop-opacity="0.7"/>
      <stop offset="1" stop-color="{SIGNAL}" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="ink" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffffff"/><stop offset="1" stop-color="#aab8cc"/>
    </linearGradient>
    <linearGradient id="sweep" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="{SIGNAL}" stop-opacity="0"/>
      <stop offset="0.5" stop-color="{SIGNAL}" stop-opacity="0.8"/>
      <stop offset="1" stop-color="{PULSE}" stop-opacity="0"/>
    </linearGradient>
    <filter id="soft" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="1.1"/></filter>
    <filter id="glow" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="7"/></filter>
    {''.join(grads)}
    <style>
      @keyframes shim {{ 0%,100%{{opacity:.25}} 50%{{opacity:.85}} }}
      @keyframes pulse {{ 0%,100%{{opacity:.6;transform:scale(.96)}} 50%{{opacity:1;transform:scale(1.06)}} }}
      @keyframes scan {{ 0%{{transform:translateX(-260px)}} 100%{{transform:translateX({W}px)}} }}
      @keyframes flick {{ 0%,100%{{opacity:.5}} 50%{{opacity:.95}} }}
      .core{{transform-box:fill-box;transform-origin:center;animation:pulse 3.6s ease-in-out infinite}}
      .scan{{animation:scan 6s linear infinite}}
      .flick{{animation:flick 3s ease-in-out infinite}}
      @media (prefers-reduced-motion: reduce){{
        line{{animation:none!important}} .core,.scan,.flick{{animation:none}} .scan{{opacity:0}}
      }}
    </style>
  </defs>

  <rect width="{W}" height="{H}" fill="{VOID}"/>
  <rect width="{W}" height="{H}" fill="url(#halo)"/>
  {stars}
  <g>{''.join(rays)}</g>
  <circle class="core" cx="{FX}" cy="{FY}" r="120" fill="url(#core)" filter="url(#glow)"/>
  <circle class="core" cx="{FX}" cy="{FY}" r="36" fill="url(#core)"/>

  <!-- wordmark (crisp vector) -->
  <g transform="translate(74 322) scale(0.84 1)">
    <text x="0" y="0" font-family="{COND}" font-weight="800" font-size="172" letter-spacing="-3" fill="{SIGNAL}" opacity="0.35" filter="url(#glow)">SHIFT-9</text>
    <text x="0" y="0" font-family="{COND}" font-weight="800" font-size="172" letter-spacing="-3" fill="url(#ink)">SHIFT<tspan fill="{SIGNAL}">-9</tspan></text>
  </g>
  <text x="78" y="366" fill="{MUTED}" font-family="{MONO}" font-size="19" letter-spacing="8" class="flick">CODE EXECUTION IN MOTION</text>

  <!-- instrument frame -->
  <rect class="scan" x="0" y="0" width="260" height="{H}" fill="url(#sweep)" opacity="0.32"/>
  <rect x="6" y="6" width="{W-12}" height="{H-12}" fill="none" stroke="{SIGNAL}" stroke-opacity="0.20" stroke-width="1.5"/>
  <g stroke="{SIGNAL}" stroke-width="2.5" fill="none" opacity="0.9">
    <path d="M6 34V6H34"/><path d="M{W-34} 6H{W-6}V34"/>
    <path d="M6 {H-34}V{H-6}H34"/><path d="M{W-6} {H-34}V{H-6}H{W-34}"/>
  </g>
  <text x="40" y="36" fill="{MUTED}" font-family="{MONO}" font-size="15" letter-spacing="5" class="flick">SHIFT-9 // INSTRUMENT</text>
  <text x="{W-40}" y="{H-22}" fill="{MUTED}" font-family="{MONO}" font-size="15" letter-spacing="5" text-anchor="end">X:001 · Y:STUDIO</text>
</svg>
'''

with open(OUT, "w") as f:
    f.write(svg)
print(f"  assets/s9-banner.svg  ({W}x{H}, {len(svg)//1024} KB, fully vector)")
