// Public editorial entries, newest first. Keep private source records out of this file.
export const DEV_LOG = [
  {
    n: "Jev can't write, so I gave him a voice",
    s: "30 SEP 2026",
    sc: "dev" as const,
    d: "Jev can't write, so I gave him a voice anyway. In the Line, my chat room in the Control Plane, a plain message becomes a choice among 17 complete replies I wrote ahead of time. His pick comes back word for word, with no writing model in between. His first real answer, \"this needs an executor\", was correct. The first review failed it, the second passed. Still on a branch.",
  },
  {
    n: "A hackathon, a bot and three weeks",
    s: "28 SEP 2026",
    sc: "rnd" as const,
    d: "I joined Building with IBM Bob, a virtual hackathon run by IBM and AngelHack. It opens September 28 and runs through October 18, so I have three weeks to build something while my other projects keep asking for attention. I registered on September 22, and I'll write up what I make once there's something worth showing.",
  },
  {
    n: "Fixing the audit list without declaring victory",
    s: "28 SEP 2026",
    sc: "dev" as const,
    d: "I asked for everything my audit flagged to be fixed and proven. It covered 140 claims, 21 of them flagged, plus 23 order cases and 248 old items. Repairs landed in the Control Plane's screen sizing, the video pipeline, the Feelspoon app (69 unit and 42 database checks) and a game build (160 headless checks). The ledger still says open, so I'm not calling it done.",
  },
  {
    n: "Grilling Jev about the whole Control Plane",
    s: "27 SEP 2026",
    sc: "dev" as const,
    d: "I put six rounds of questions to Jev about the whole Control Plane, scoring 24 problems I'd already checked that day. Asked whether it can deliver what I want today, he said yes at 29%, which is a no. The build press ranked first to fix: 49 build errors in 14 days, never one finished build. I fixed nothing in that session. Fair, if humbling.",
  },
  {
    n: "The brain writes its own homework",
    s: "27 SEP 2026",
    sc: "dev" as const,
    d: "My notes system now writes its own homework. A daily job wrote a lessons page eight days running, session ingests staged anywhere from 2 to 31 new notes per run, and the wiki gained 4 pages with 29 updated. I also backfilled two missing records. Whether the lessons are any good is the next question.",
  },
  {
    n: "Private means checked",
    s: "27 SEP 2026",
    sc: "dev" as const,
    d: "My video pipeline archives finished work to private storage, but creating a repo as private doesn't prove an existing one is. Now the archive checks first and refuses to upload unless private is confirmed. Both new tests failed before the fix, and 122 passed after. I also fixed one banned word in an episode 4 stock query. No real upload ran, so remote archiving is still unproven.",
  },
  {
    n: "Nothing is done until Jev says so",
    s: "26 SEP 2026",
    sc: "dev" as const,
    d: "I made Jev the yes or no before any merge and before a build can call itself done. My first bar of 98% rejected finished work, so I measured it and moved to 90% on a better question. Finished code passed at 94%. The same code without its test scored 27%. I can still override him, on purpose.",
  },
  {
    n: "A health check was spending my money",
    s: "26 SEP 2026",
    sc: "dev" as const,
    d: "I traced a week of paid model usage through my gateway record: 14,259 requests and 5.88 million tokens. One health probe asking a paid model for a single token every 30 seconds made 13,457 of them. My first fix missed it. The second removed it, and the next 21 minutes showed zero calls. Four seats I set by hand could still spend, so that part is still my call.",
  },
  {
    n: "Apparently \"unlimited\" needs a limit",
    s: "25 SEP 2026",
    sc: "rnd" as const,
    d: "Feelspoon's paywall promised \"without limits\", but the server caps every account at 40 AI captures a day. I cut it down to what Premium really adds. I also fixed a recipe crash on ingredients with no quantity or unit. The crash fix is in build 10, the paywall lands in the next build, and the Play listing still says unlimited until I approve the fix.",
  },
  {
    n: "Everyone gets a daily stand-up",
    s: "25 SEP 2026",
    sc: "dev" as const,
    d: "Every agent now has a stand-up at 7:00 each morning, built from all 66 projects in my Dev folder. The first run had 9 of 10 agents speak, and every agent now gets the last 14 days of minutes. My first attempt crashed by pasting a 100 KB stand-up into a single command line. Nobody sits down, which may be why it works.",
  },
  {
    n: "Teaching the taste library to read other sites",
    s: "24 SEP 2026",
    sc: "rnd" as const,
    d: "The taste library now captures elements from reference sites and videos, with its tokens renamed to Shift-9. I pointed a model at one component site and found 6,153 pages. The first two were indexed end to end, with a model watching each preview and a judge deciding. A full pass would take about 110 hours of model time. That's a lot of watching someone else's buttons.",
  },
  {
    n: "Letting an agent drive the game editor",
    s: "24 SEP 2026",
    sc: "rnd" as const,
    d: "I gave HoopClone an editor add-on of 81 files so my coding agents can drive the game editor directly, plus the project settings it needs. The data tests now number 35 and all pass, up from 9. A game-side test runner exists, but I haven't run it yet. The game itself is still a work in progress.",
  },
  {
    n: "Vespers learns to fall apart",
    s: "24 SEP 2026",
    sc: "rnd" as const,
    d: "I added breakable props, ground pieces that come apart, a benchmark script and a ground shader to Vespers, plus new sound effects. None of it is in a build you can run. The package on disk is still the one from August 26, so rebuilding it and actually looking is next. Breaking things turned out to be the easy part.",
  },
  {
    n: "Giving every agent the same memory",
    s: "23 SEP 2026",
    sc: "dev" as const,
    d: "I wired fresh notes from my knowledge base into the agents that take work in the Control Plane. I also had all 110 pending old sessions read: the ledger grew from 537 to 647, 47 sessions taught nothing new, and 4 became takeaway notes. Eight real hook runs fetched real notes, but I never launched a fresh interactive session to watch it work.",
  },
  {
    n: "Feelspoon gets a community",
    s: "23 SEP 2026",
    sc: "rnd" as const,
    d: "Feelspoon 1.0.2 adds a community: 30 achievement stickers for your boards, cook pages, a weekly challenge, an \"I cooked this\" button, notes and photos, an activity inbox and a way to block people. The sticker set passed 54 tests. Build 10 went to Google on September 25. I haven't confirmed it's live yet.",
  },
  {
    n: "Feelspoon on a laptop is not a phone in a box",
    s: "21 SEP 2026",
    sc: "rnd" as const,
    d: "On a laptop, the Feelspoon web app looked like a phone floating in the middle of the page. I removed the capped column and sized every screen to its device, with phone, foldable, tablet and desktop tiers. Filter rows wrap instead of cutting off, and the tabs stay along the bottom. The source is done. The live page still needs a proper look.",
  },
  {
    n: "Feelspoon's microphone kept hearing itself",
    s: "21 SEP 2026",
    sc: "rnd" as const,
    d: "In cooking mode, Feelspoon's microphone now ignores the app's own voice, and no transcript sits over the mic. I also found the mic button sitting on top of other buttons. On the paywall it covered Subscribe, so it steps aside there now. An app that listens should at least stop listening to itself.",
  },
  {
    n: "Glitter out, real spice in",
    s: "21 SEP 2026",
    sc: "rnd" as const,
    d: "The Feelspoon site lost its glitter cursor trail and gained a pinch of real spice, dropped from a camera looking straight down onto the table in the photo, never onto text. feelspoon.app/app now opens the web app, the official Play badge is in, and the hero photo went from 2 MB to 134 KB. Both pull requests are merged.",
  },
  {
    n: "Half is not one",
    s: "20 SEP 2026",
    sc: "rnd" as const,
    d: "Feelspoon 1.0.1 added smart swaps, the feature my website was advertising and the app didn't have. Each ingredient offers a substitution with the caveat that decides whether it works, and the amount scales. I also found a plain 1/2 being read as 1, so every fraction in a scaled recipe or shopping list was wrong. Apparently the numerator is not the whole story.",
  },
  {
    n: "The curtain lasted one minute",
    s: "18 SEP 2026",
    sc: "dev" as const,
    d: "I tried opening the studio with a curtain handoff and reverted it 51 seconds later. The wallpapers stuck. The studio now has selectable wallpapers, the yarn entrance is back, and the desktop return works again. Both pull requests merged the same evening. Some ideas need to be seen exactly once.",
  },
  {
    n: "The video is out. The pipeline has notes.",
    s: "17 SEP 2026",
    sc: "dev" as const,
    d: "By September 17, Short 7 was public on Bring Up Desk. I also worked on a recovery path for an oversized cover image: it can prepare a smaller upload copy without changing the approved source, recognise a video that is already public, and reconnect the dashboard when its status feed drops. The repair is still in testing and review. The goal is less babysitting, with a dashboard that tells me what actually happened.",
  },
  {
    n: "Flow State gets an Ubuntu address",
    s: "17 SEP 2026",
    sc: "rnd" as const,
    d: "I took Flow State another step beyond Windows with an Ubuntu X11 preview that puts spoken words into a real editor. Ten recorded-audio trials delivered the exact text, and the offline installer was checked through install, upgrade and removal without losing the user's dictionary. This covers the Ubuntu X11 setup; broader Linux and Wayland support are still ahead.",
  },
  {
    n: "Apparently apps do not market themselves",
    s: "17 SEP 2026",
    sc: "rnd" as const,
    d: "I started a focused growth push for Feelspoon, with social posts and eight personal introductions to food creators and Android reviewers. The campaign links straight to Google Play while the website catches up. There are no install, subscription or revenue results to claim yet. Apparently pressing publish on an app does not also summon its audience.",
  },
  {
    n: "A graveyard with something to break",
    s: "12 SEP 2026",
    sc: "rnd" as const,
    d: "I worked with a specialist crew in Grok on Vespers' graveyard: separate stones over dirt, layers of moss and wear, and breakable props with fire surviving on the debris. The aim is a place that reacts when you hit it. A haunted wallpaper can only carry a game so far. This is still a work in progress, with some prop details and final visual approval outstanding.",
  },
  {
    n: "Basketball players need the right skeleton",
    s: "10 SEP 2026",
    sc: "rnd" as const,
    d: "HoopClone's players were having a rough time with basic anatomy. The jersey model was attached to an incompatible skeleton, and the players were also facing the wrong way. I repaired both and checked the result in actual five-on-five footage. Feet, stops, defensive slides and ball contact still need work, but getting everyone pointed in the right direction feels like a reasonable first demand of a basketball team.",
  },
  {
    n: "Apparently files aren't small enough yet",
    s: "22 AUG 2026",
    sc: "rnd" as const,
    d: "I've been chasing a better way to squeeze big piles of files down. With s9, I tested removing repeated chunks before compressing what remained. The corrected benchmarks found useful gains on some repetitive data, and a scan of my project files found plenty of exact duplicates. There is a tradeoff between smaller archives and quickly pulling out one file. Still an experiment, still chasing the bigger idea. Physics has declined to make my random bytes smaller.",
  },
  {
    n: "Freezing a golden dataset before comparing models",
    s: "01 SEP 2026",
    sc: "dev" as const,
    d: "Established 50 seed evaluation cases across five model job classes, with exact-answer, contains, schema and rubric-based scoring. Case hashes make the dataset add-only: changed or missing cases fail validation instead of quietly improving an average. The runner starts the bridge from the configuration under test and records a result for every case. Added a separate set of 50 retrieval cases against a frozen document corpus, so answer quality and retrieval quality can be measured without moving the reference material between runs.",
  },
  {
    n: "Making LLM-as-judge rubrics versioned and inspectable",
    s: "02 SEP 2026",
    sc: "dev" as const,
    d: "Separated answer-rubric grading from retrieval grading with immutable, versioned system prompts and an explicit prompt registry. General grading returns pass and a reason; retrieval grading returns separate faithfulness and relevance verdicts in one structured response. This repaired a real mismatch where the judge followed a pass/fail system prompt while the evaluator expected different fields. Missing or malformed judgments retain their failure reason. The design makes grading criteria inspectable and keeps retrieval support distinct from whether an answer addresses the question.",
  },
  {
    n: "Keeping model decisions traceable to their inputs",
    s: "01 SEP 2026",
    sc: "dev" as const,
    d: "Added a SQLite trace store that references deduplicated prompts by SHA-256 rather than copying prompt text into every request record. Traces retain model and provider identity, latency, token usage, fallback activity, cache state and schema-repair history; strings pass through redaction before storage. Task identifiers and loaded-kit receipts connect model calls to the work that requested them. Versioned prompt pins preserve the wording behind an older result, providing a concrete audit trail for later evaluation and debugging.",
  },
  {
    n: "Combining lexical and semantic retrieval in SQLite",
    s: "01 SEP 2026",
    sc: "dev" as const,
    d: "Built a hybrid RAG index using SQLite FTS5 for keyword matching and sqlite-vec for vector similarity. Reciprocal Rank Fusion combines both rankings at k=60, producing 30 candidates before reranking selects five passages. Hash-based ingestion updates changed files, while source paths, line ranges and heading metadata remain attached to chunks. Repository, project, path-prefix and time filters constrain retrieval. Embedding and reranking use the same model bridge as generation, keeping provider routing outside the retrieval implementation.",
  },
  {
    n: "Enforcing citations at the answer boundary",
    s: "02 SEP 2026",
    sc: "dev" as const,
    d: "Made the RAG answer path require a structured answer and citations drawn only from the passages actually supplied. Empty citations, unknown references, malformed replies and empty retrieval replace the answer with NOT_FOUND and retain a diagnostic reason. Numbered passage tokens resolve back to stable chunk IDs in code, removing hash-transcription errors without expanding the set of acceptable sources. Tests exercise valid, missing, out-of-range and out-of-context references. Citation membership establishes traceability; semantic faithfulness remains a separate evaluation.",
  },
  {
    n: "Recording retrieval scores without hiding answer failures",
    s: "02 SEP 2026",
    sc: "dev" as const,
    d: "The archived 50-case RAG evaluation recorded 100% context recall, 98.8% context precision, 98% judged faithfulness and 100% answer relevance, with all 50 cases measured for each metric. Those recorded values exceeded the configured floors of 80%, 80%, 90% and 85%. The same run's separate direct-answer pass scored 29 of 60; its retrieval-oriented questions were asked without supplied passages and exposed unsupported answers. These are distinct test paths and a dated measurement, not a claim that the complete system passed or that current evaluation integrity has been established.",
  },
  {
    n: "Turning release requirements into twelve executable gates",
    s: "01 SEP 2026",
    sc: "dev" as const,
    d: "Implemented an ordered twelve-gate workflow spanning specification checks, test evidence, mutation testing, competitive comparison, adversarial review, static analysis, visual inspection and release controls. The phase's conformance record reports all twelve passing. A real integration fault surfaced when Git environment variables inherited from a hook made checks inspect the wrong repository; a shared child-process environment fix was then verified under the same inherited variables. Gate execution now has a recorded task and result rather than relying on an agent's statement that checks were run.",
  },
  {
    n: "Shadow-testing changes before moving a model configuration",
    s: "02 SEP 2026",
    sc: "dev" as const,
    d: "Built a candidate workflow that clusters recorded failures by reason, proposes one configuration variable at a time and compares the candidate against a pinned baseline. Its promotion checks compare golden-set improvement, previously passing cases and replay quality. Shadow traces are marked to distinguish them from production traffic, and a rollback path can restore the previous pin. A later review identified gaps in how incomplete retrieval and replay evidence reaches the promotion decision; those checks need repair before this can be described as a fully enforced release boundary. This entry records the workflow's implementation, not complete system clearance.",
  },
  {
    n: "Converting repaired production failures into regression cases",
    s: "02 SEP 2026",
    sc: "dev" as const,
    d: "Connected production trace scoring to add-only golden-dataset growth. A case qualifies only when the same input first scores below its floor and later scores above it after a promotion, avoiding the mistake of treating an ordinary lucky retry as a proven repair. New cases assert the absence of the recorded defect through a schema check or targeted rubric, rather than memorizing the successful answer. Existing case hashes remain protected, preserving the regression set while adding evidence from actual failure patterns.",
  },
  {
    n: "Repairing orchestration routes against installed capabilities",
    s: "28 AUG 2026",
    sc: "dev" as const,
    d: "Audited a task router that directed work to six harnesses that did not yet exist. The repaired router selects installed capabilities and reports a broken route when a target disappears. The recorded ten-prompt check moved from seven failures to ten passes, with an intentionally broken route proving the check could fail. Shared model tools also gained a start-if-down gateway path, verified by recovering a stopped gateway and receiving a real model answer from outside the project directory. This establishes the dated routing repair, not blanket availability of every later capability.",
  },
  {
    n: "Testing external data before it reaches the application",
    s: "06 JUL 2026",
    sc: "dev" as const,
    d: "Added network-free provider-data regressions to an earlier media-tooling project. Fixtures cover paginated Spotify metadata, missing and null records, Unicode fields and error propagation, alongside SoundCloud record hydration, order preservation and playlist deduplication. The tests exercise normalization at the integration boundary without depending on live accounts or provider availability. This is historical work in a retired project, retained here as an engineering milestone rather than an active product claim.",
  },
  {
    n: "Building family relationships from cited records",
    s: "05 SEP 2026",
    sc: "rnd" as const,
    d: "Extended the KinQuest genealogy prototype toward automatic record-page reading and recursive discovery through explicit relationship statements in obituaries. The research model distinguishes candidate matches from supported relationships, retains source evidence and supports person-centered trees. A saved development checkpoint reconstructed a small cited relationship graph and added sibling-record expansion. The complete name-to-extended-tree workflow remains unfinished and these changes were not deployed. The engineering focus is evidence-preserving discovery without presenting a name match as a proven family connection.",
  },
  {
    n: "Measuring a horde simulation on integrated graphics",
    s: "03 AUG 2026",
    sc: "rnd" as const,
    d: "Built Vespers' horde combat around batched MultiMesh rendering and packed enemy data rather than one scene node per enemy. The August 3 packaged Windows benchmark recorded 905 peak enemies and 430 simultaneous effects over a 14-second run, averaging 251.3 FPS on Intel Iris Xe at a 1280 × 720 window with the game's lower internal rendering resolution. The report identifies the executable so packaged and editor results cannot be conflated. This is a dated, controlled benchmark of the prototype, not a guarantee for every scene or device.",
  },
  {
    n: "Learning speech corrections only after review",
    s: "14 JUL 2026",
    sc: "rnd" as const,
    d: "Added a local accuracy-learning pipeline to Flow State. Token-level diffs extract short replacements only inside the trusted dictated range; ordinary insertions and deletions are excluded so general editing is not mislearned as a speech correction. Candidates enter a pending, approved or rejected review state, and only approved mappings affect later text. An atomic local store and feature, runtime and Hub regression tests cover the path. Personalization stays explicit and reviewable instead of silently rewriting the user's vocabulary.",
  },
  {
    n: "Recovering dictation after an interrupted session",
    s: "12 JUL 2026",
    sc: "rnd" as const,
    d: "Introduced an append-only JSONL recovery journal for Flow State's partial transcripts. Each event is flushed and fsynced before returning, while validated session IDs and path containment keep recovery operations inside the owned directory. Interrupted sessions can be reconstructed from surviving events, including when a malformed line is present; completed sessions remove their own journal. Regression tests cover reconstruction and refusal to delete outside the recovery area. The journal provides a durable checkpoint before the final transcript reaches normal history.",
  },
  {
    n: "Shipping store-listing changes as a verified transaction",
    s: "06 SEP 2026",
    sc: "rnd" as const,
    d: "Built Feelspoon's Google Play listing update around the Developer API's edit transaction. The tool validates copy limits, replaces screenshots slot by slot, reads the listing back and commits only when the returned state matches; a failed verification discards the edit. A companion compositor produces captioned phone, seven-inch and ten-inch tablet frames from app captures, with device-specific crops. The September 6 listing update was pushed through this path, replacing an unreliable browser-edit workflow with repeatable validation.",
  },
  {
    n: "Making agent context an executable contract",
    s: "08 SEP 2026",
    sc: "dev" as const,
    d: "Hardened Vespermesh's Claude Code and Codex review adapters so they receive the current operating rules and inventory, with source receipts, separately from untrusted repository content. Missing, oversized or changed context blocks dispatch; changes during a review prevent its result from being accepted. The local suite passed 59 tests, and the compiled Control Plane integration passed six checks. Removing the operating text made both adapter tests fail. These are isolated execution proofs; live-provider review remains a separate check.",
  },
  {
    n: "Testing the boundaries of a local publishing tool",
    s: "08 SEP 2026",
    sc: "dev" as const,
    d: "Hardened the Feelspoon Growth Kit's local HTTP boundary with Host and Origin validation, loopback-only listening, restricted editable fields and escaped HTML attributes and image values. Two regression suites included 32 isolated HTTP requests and failures against the old implementation. After activation, real requests returned 200 for the local page and 403 for invalid Host or Origin values. The four content stores remained byte-identical, and publishing still requires owner approval.",
  },
  {
    n: "Hardening projection control at the network boundary",
    s: "08 SEP 2026",
    sc: "rnd" as const,
    d: "Repaired Lumen's HTTP sibling-directory traversal, malformed Range handling and null WebSocket-message crash, alongside an Electron runtime update. Regression coverage exercises real network requests and archive-extraction escape attempts. Both existing renderer pages then loaded in an isolated Electron smoke test that exercised pairing, blackout and the homography controls used for corner-pin projection, with no renderer errors. This verifies the local software paths; projector, media and hotplug testing remain open.",
  },
  {
    n: "Patching the mobile bundler without changing the app framework",
    s: "08 SEP 2026",
    sc: "rnd" as const,
    d: "Updated Feelspoon's compatible Metro dependency family to remove a vulnerable image decoder without changing Expo, React Native or the app's declared dependencies. The installed-project audit moved from five high-severity findings to zero high; 19 moderate findings remain. A new pretest runs Metro's real PNG dimension, metadata and asset-hash pipeline, rejects malformed input and fails against the old decoder. All 15 Jest tests and TypeScript passed locally. A native build and release are separate milestones.",
  },
  {
    n: "Binding image approval to the assets actually reviewed",
    s: "08 SEP 2026",
    sc: "dev" as const,
    d: "The video pipeline now derives picture-approval status from a complete, matching approval record rather than the existence of a PNG. Generation requests the target aspect ratio without stretching returned pixels, preserves replaced identity seeds, and resumes only failed shots. Complete image sets can reach owner review with visible quality warnings; incomplete sets still stop, and exact hash-bound owner approval gates the build. The standard suite passed 981 tests, with two skipped and one deselected. The current episode's clips and final render are still pending.",
  },
  {
    n: "Giving image generation a second provider path",
    s: "07 SEP 2026",
    sc: "dev" as const,
    d: "Extended the still-image tool to fall back from Google's exhausted quota to Hugging Face Inference Providers, using provider-specific model mappings and response handling. A real fallback produced a 1152 × 768 PNG in 4.4 seconds, followed by a successful two-image Growth Kit batch. The path uses inference-provider allocation rather than the separate GPU allocation reserved for video. This adds a measured recovery route while keeping resource accounting explicit.",
  },
  {
    n: "Proving a fresh LLM response is actually fresh",
    s: "06 SEP 2026",
    sc: "dev" as const,
    d: "Traced repeated LLM answers to the internal bridge cache: the caller requested fresh inference, but its flag never reached the bridge and cached replies were labeled fresh. The fix propagates freshness across the HTTP boundary, reports cache age and distinguishes idempotent replay from a cache miss. Fresh callers now require positive provider-attempt evidence and reject stale rescue, replay or missing evidence. A deliberately misleading fake bridge exercises 19 checks, including stripped headers; ten failed before the fix. Live repeat-request probes then confirmed the repaired path.",
  },
  {
    n: "Verifying dependency repairs through native image processing",
    s: "06 SEP 2026",
    sc: "dev" as const,
    d: "Prepared a targeted security update for both studio web apps, covering Next.js, PostCSS and Sharp's native image stack. A build gate resolves the installed packages, enforces patched version floors and invokes Next's actual PNG, JPEG, WebP and AVIF optimizer paths. The original PostCSS installation failed the gate; the patched tree passed all four conversions, both production builds and a zero-finding dependency audit. This is verified local build work, pending deployment; Windows native-library checks do not establish cross-platform behavior.",
  },
  {
    n: "Separating model identity from provider availability",
    s: "05 SEP 2026",
    sc: "dev" as const,
    d: "Refactored the shared model layer beneath 27 existing callers to support multiple provider routes without rewriting their call sites. Live catalogues supply model availability and capability data; substitutions return resolvedFrom instead of silently changing identity. The independent-review lineage guard now rejects unknown model families and cross-family fallbacks. A catalogue check was driven red with a retired model ID, then restored green. Chat models and embedding endpoints are checked separately so an unavailable catalogue is not mistaken for a missing model.",
  },
  {
    n: "Turning session history into a checked knowledge index",
    s: "05 SEP 2026",
    sc: "dev" as const,
    d: "Built a repeatable triage pass over 537 captured sessions to recover decisions, corrections and failure patterns instead of indexing entire conversations as guidance. The pass identified 133 sessions carrying signal and recovered 126 earlier user statements; a second run recovered nothing again. A generated, tagged contents page connects notes to their source locations, while drift checks rebuild and compare it. Duplicate detection also checks bodies and repository ownership, avoiding false matches between similarly titled lessons or cross-repository paths.",
  },
  {
    n: "Bringing the room closer to the film",
    s: "06 SEP 2026",
    sc: "dev" as const,
    d: "The latest room pass focuses on continuity between the opening film and the room you can explore. The monitor arrangement, printer bay and two-cube Lumen stack were adjusted against the opening still, with the printer on the left and Lumen immediately to the right. This room update is in progress and is being refined before release.",
  },
  {
    n: "A different surface for Flow State",
    s: "05 SEP 2026",
    sc: "rnd" as const,
    d: "Flow State’s page moved to an interactive ripple effect, replacing the earlier water surface. The effect responds to the pointer, bending the page around its content where the browser supports it. Other browsers keep the readable page with a lighter visual treatment. The aim is to give the page a sense of water without putting the effect in the way of reading.",
  },
  {
    n: "A clearer path to Feelspoon",
    s: "05 SEP 2026",
    sc: "rnd" as const,
    d: "The Feelspoon hero’s main link was updated to point to Google Play. A small change to the studio page, with a direct purpose: someone interested in the app can get from the introduction to its store listing.",
  },
  {
    n: "Keeping approved video assets intact",
    s: "06 SEP 2026",
    sc: "rnd" as const,
    d: "The video-production pipeline gained checks that preserve approved covers and distinguish a genuine render retry from a repeated request. Writer fallbacks also continue when a provider returns an unusable reply. The work focuses on keeping an approved video consistent as it moves from writing through rendering.",
  },
  {
    n: "More reliable development checks",
    s: "06 SEP 2026",
    sc: "dev" as const,
    d: "Repaired the Control Plane's runtime declaration, reproducible installation path and self-test failure reporting. The LLM fallback tests also gained explicit bridge isolation and an empty credential-store fixture after routing changes had sent supposed test calls to real providers. The isolated fallback suite passed 26 checks. By the September 8 follow-up, the full local run passed 1,007 server checks and 21 required repair suites with no skips, while keeping installed-hook and live-provider verification distinct from offline test results.",
  },
  {
    n: "Two stages of video approval",
    s: "05 SEP 2026",
    sc: "rnd" as const,
    d: "Added two stages of video-asset approval to the production workflow. These create explicit review checkpoints before production continues, while keeping the final publication decision with a person.",
  },
  {
    n: "Making the studio easier to find and use",
    s: "05 SEP 2026",
    sc: "rnd" as const,
    d: "Updated the site's robots and sitemap configuration alongside accessibility improvements and lighter font and poster assets. This pass addressed discoverability, navigation, and loading weight within the existing studio experience.",
  },
  {
    n: "Taking Flow State toward Linux",
    s: "03 SEP 2026",
    sc: "rnd" as const,
    d: "Moved 28 operating-system call sites out of Flow State's dictation and Hub modules into a shared platform interface, then began the Linux X11 implementation. Windows APIs, hotkeys and registry access now sit behind that boundary instead of being interleaved with speech and interface logic. The recorded Windows suite passed 226 tests, including 25 platform-layer checks. Linux support remains in progress; the abstraction and Windows regression results are not a Linux release claim.",
  },
  {
    n: "Dictation without stealing the keyboard",
    s: "03 SEP 2026",
    sc: "rnd" as const,
    d: "Added a native focus regression for Flow State's floating dictation pill: read the WS_EX_NOACTIVATE window style back from the live window, then type real keys into another window while the pill is visible. This checks the behavior a screenshot cannot establish: dictation controls must not intercept the user's typing. Related test isolation keeps routine suite execution from taking over the working screen. The result is a concrete Windows integration check around the application's least intrusive interface.",
  },
  {
    n: "A more usable publishing workspace",
    s: "03 SEP 2026",
    sc: "dev" as const,
    d: "Built out the local workspace for drafting and queuing Feelspoon social posts. Changes added publishing connections, image-generation fallbacks, and JPEG output suited to the destination platforms. Removals became undoable and failures became visible, making accidental removals recoverable and failures easier to notice.",
  },
  {
    n: "Bringing video production into one workspace",
    s: "31 AUG 2026",
    sc: "rnd" as const,
    d: "Work on the hardware-video pipeline connected research, scripts, narration, sound, imagery, rendering, and private draft uploads. This pass consolidated the sound kit and image supply. The workflow prepares a video for review; publication remains a separate human decision.",
  },
  {
    n: "Studying how interfaces actually behave",
    s: "28 AUG 2026",
    sc: "dev" as const,
    d: "Organized a reference library of websites with measured visual properties. The library supports research into typography, color, layout, and interaction when developing studio interfaces. References are design-study material, not claims of authorship.",
  },
  {
    n: "Giving the Vespers enemies distinct identities",
    s: "26 AUG 2026",
    sc: "rnd" as const,
    d: "The game art pass replaced reused recolors with distinct enemy faces and refined the lantern wisp and wax revenant. Related work adjusted damage-number sizing for the game's display and prepared music for its moon phases. These are development milestones in the game's visual and audio identity.",
  },
  {
    n: "Keeping video review available",
    s: "26 AUG 2026",
    sc: "dev" as const,
    d: "Added a fallback sequence for video-capable models so one unavailable provider does not leave a clip unreviewed. Earlier work connected live viewing, screen captures, and short recordings. The purpose is to inspect the rendered result, including motion, rather than infer its appearance from code.",
  },
  {
    n: "Feelspoon reaches Android submission",
    s: "24 AUG 2026",
    sc: "rnd" as const,
    d: "The recipe-organizer project reached a recorded Google Play submission milestone, with feelspoon.app and the studio's product links updated during release preparation. Feelspoon brings recipe saving, hands-free cooking, meal planning, and shopping lists into one product. This entry records the submission date; it does not imply every platform launched that day.",
  },
  {
    n: "Building a softer learning world",
    s: "22 AUG 2026",
    sc: "rnd" as const,
    d: "Developed a sky world with a shader-driven sky, wool-like assets made in Blender, and floating islands. Further art work refined story pages and character placement. The direction gives the children's learning prototype a consistent, tactile setting across its screens.",
  },
  {
    n: "A clearer art direction for Midnight Returns",
    s: "22 AUG 2026",
    sc: "rnd" as const,
    d: "Added game art, a 3D knight, and a design brief to the Metroidvania project. These assets extend earlier work on animation sheets and deterministic gameplay tests. The entry marks the development of the game's identity, not a finished game release.",
  },
  {
    n: "Making dictation settings easier to tune",
    s: "22 AUG 2026",
    sc: "rnd" as const,
    d: "Added settings for the floating pill alongside a workbench page. The work exposes controls for the small interface used during dictation, so its presentation can be adjusted without treating the whole application as a single fixed layout.",
  },
  {
    n: "Comparing a render with a video reference",
    s: "20 AUG 2026",
    sc: "dev" as const,
    d: "Added a review path that compares a local render with a video reference. This extends visual inspection beyond still images: timing and transitions need to be viewed as motion. The tool supports review of the actual output before delivery.",
  },
  {
    n: "Exploring spatial navigation for mission control",
    s: "16 AUG 2026",
    sc: "rnd" as const,
    d: "Prototyped a command interface with WebGL cards, zoom transitions, and a card-to-room dossier interaction. The work explores whether navigation can preserve a sense of place while revealing more detail. It remains interface development, separate from the public studio's room experience.",
  },
  {
    n: "Previewable starting points for sites and games",
    s: "16 AUG 2026",
    sc: "dev" as const,
    d: "Added preview support to reusable project kits and created companion website and game proofs. The focus is checking a starting point before extending it into a project, with visible examples that expose outdated assumptions early.",
  },
  {
    n: "Bounded work in a persistent assistant",
    s: "04 AUG 2026",
    sc: "dev" as const,
    d: "Added a time limit to daily debrief processing so a stalled model call cannot block the rest of a knowledge-sync workflow. This is part of the broader work on reusable agent skills, persistent project context, and continuity between development sessions.",
  },
  {
    n: "Keeping research attached to video production",
    s: "03 AUG 2026",
    sc: "dev" as const,
    d: "Strengthened source provenance in the video pipeline and added a recurring research component. Related production work made uploads resumable and guarded against duplicate uploads. The aim is to preserve both the research trail and the state of a production run.",
  },
  {
    n: "An evidence-first mission-control prototype",
    s: "01 AUG 2026",
    sc: "rnd" as const,
    d: "Built a connected prototype covering mission tracking, a GitHub App connection flow, and an isolated Docker test environment. Work also hardened the live client connection. The design makes evidence and explicit project rules part of the development workflow instead of leaving them only in documentation.",
  },
  {
    n: "A cleaner waitlist flow",
    s: "01 AUG 2026",
    sc: "rnd" as const,
    d: "Work on Flow State's studio page included the waitlist and duplicate-signup handling. The change treats registration as a complete interaction: entering an address should lead to a clear result, including when that address has already been registered.",
  },
  {
    n: "Reusable assets from generation to extraction",
    s: "29 JUL 2026",
    sc: "dev" as const,
    d: "Established an asset library with base bodies and a generate-then-cut workflow. Separating source generation from asset extraction creates reusable pieces for later visual work instead of tying every output to one composition.",
  },
  {
    n: "Building the Vespera / KAGE combat prototype",
    s: "22 JUL 2026",
    sc: "rnd" as const,
    d: "The prototype progressed through movement and dashing, pooled enemies and waves, weapons and collisions, and roguelite progression. Later work added boss states, achievements, and a visual overhaul. Object pooling and spatial partitioning support the dense combat scenes this style of game requires.",
  },
  {
    n: "Controlling projection mapping from a phone",
    s: "15 JUL 2026",
    sc: "rnd" as const,
    d: "The project record describes a projection-mapping prototype with corner-pin adjustment and live phone control over WebSocket. A matrix transform fits the projected image to its target surface. This dated project checkpoint documents the approach; it is not a claim of a new release that day.",
  },
  {
    n: "A local-first dictation workspace",
    s: "09 JUL 2026",
    sc: "rnd" as const,
    d: "The Windows dictation build brought together history, dictionary, audio, appearance, and privacy settings with a tray interface and floating pill. Recovery work retained audio segments for interrupted sessions. The product direction is local speech processing with a compact interface that stays close to the user's writing.",
  },
  {
    n: "Separating basketball simulation from presentation",
    s: "08 JUL 2026",
    sc: "rnd" as const,
    d: "A refactoring pass worked on the scene and simulation structure of the Godot basketball project. Its data pipeline connects Python basketball statistics to game data and GDScript, with a player-attribute model and broadcast-style camera foundation. This is ongoing simulation development.",
  },
  {
    n: "Testing game rules independently of the scene",
    s: "06 JUL 2026",
    sc: "rnd" as const,
    d: "Added Unity EditMode tests for deterministic systems and an automated test workflow. A related fix updated the boss controller for the Cinemachine namespace. Testing the rules separately gives gameplay changes a repeatable check before they are judged in a running scene.",
  },
  {
    n: "Turning interface patterns into working demos",
    s: "30 JUN 2026",
    sc: "dev" as const,
    d: "Expanded the UI workbench with live component demos, landing-page patterns, page transitions, and foil-balloon text. The same pass replaced placeholder snippets and corrected TypeScript and motion-library integration issues. The goal is reusable examples that can be tried and adapted.",
  },
  {
    n: "A basketball prototype with real presentation assets",
    s: "29 JUN 2026",
    sc: "rnd" as const,
    d: "Added court, crowd, and jersey textures alongside a headless launch and screenshot driver. The work brings presentation assets and repeatable inspection into the Godot prototype, supporting development of its simulation and broadcast-style view.",
  },
  {
    n: "Guided Windows diagnostics",
    s: "25 JUN 2026",
    sc: "rnd" as const,
    d: "Built a native Windows utility using Flet and asynchronous Python, with guided troubleshooting, a Windows-version readout, and update-repair actions. A later pass added an installation-media action and window controls. This records the utility's development, not a recommendation to run historical repair steps on a current machine.",
  },
  {
    n: "A repeatable sprite-sheet workflow",
    s: "21 JUN 2026",
    sc: "dev" as const,
    d: "Added a sprite-sheet generator covering animation sections and an enemy bestiary. The pipeline supports the game's art production by organizing animation assets into repeatable outputs.",
  },
  {
    n: "Connecting the stages of a 3D production prototype",
    s: "19 JUN 2026",
    sc: "rnd" as const,
    d: "Implemented providers for silhouette-based voxel drafts, mesh simplification, mesh-integrity checks, skin weights, and animation retargeting. A live dashboard can resume after a dropped connection. These pieces explore a connected 3D workflow; they do not establish a finished end-to-end production suite.",
  },
  {
    n: "Ratings-driven basketball possessions",
    s: "14 JUN 2026",
    sc: "rnd" as const,
    d: "Connected imported player statistics to attributes, ratings-gated moves, passing, drives, defense, and rebounds. Team customization also feeds the scoreboard. This earlier basketball prototype explores how a deterministic simulation can drive both play and presentation.",
  },
  {
    n: "A city as a learning interface",
    s: "23 AUG 2026",
    sc: "rnd" as const,
    d: "Advisor's prototype turns learning topics into buildings in an explorable illustrated city. Custom WebGL2 shaders render the setting, while conversation happens inside the interface. This checkpoint includes one sample lesson and a working conversational flow; the broader curriculum remains in development.",
  },
  {
    n: "Reviewing the review",
    s: "12 AUG 2026",
    sc: "dev" as const,
    d: "Added an outside review layer that asks what a verdict's evidence actually supports. Separate reviewers examine the judgment, and a bounded review loop prevents repeated review from running indefinitely. This tooling keeps a passing assessment distinct from permission to release a change.",
  },
  {
    n: "An approval inbox for agent-driven work",
    s: "31 JUL 2026",
    sc: "rnd" as const,
    d: "The Gatekeeper prototype brought an approval inbox, a fleet board, and project-rule compilation into one development workflow. It explored making written rules executable and routing changes according to risk. This early project checkpoint sits alongside the work that developed into Vespermesh and the later Control Plane.",
  },
  {
    n: "A persistent workspace for specialist agents",
    s: "02 JUL 2026",
    sc: "dev" as const,
    d: "XAVIER's early architecture organized coding, writing, research, and operations into specialist roles with shared project context. Commands for briefings, decisions, and handoffs give that work a repeatable structure. The design separates the assistant's identity and routing rules from the changing state of individual projects.",
  },
  {
    n: "From session history to reusable knowledge",
    s: "02 JUL 2026",
    sc: "dev" as const,
    d: "Defined a two-tier knowledge system: active tasks and project state stay in short-term records, while durable lessons become wiki notes linked to their source material. A dedicated ingestion path preserves the original record before distilling it. This architecture supports continuity without treating every conversation as permanent guidance.",
  },
].sort((a, b) => Date.parse(b.s) - Date.parse(a.s));
